// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Army struct {
	ID          int64
	Name        string
	Description sql.NullString
}

type ArmyFaction struct {
	ID        int64
	Factionid int64
	Armyid    int64
}

type ArmyUnit struct {
	Armyid int64
	Unitid int64
	Count  int64
}

type Faction struct {
	ID          int64
	Name        string
	Description sql.NullString
}

type Game struct {
	ID           int64
	Player1id    sql.NullInt64
	Player2id    sql.NullInt64
	Player1score sql.NullInt64
	Player2score sql.NullInt64
	Winnerid     sql.NullInt64
	Matchtime    sql.NullTime
}

type Skill struct {
	ID          int64
	Name        string
	Description string
	Type        string
	Cooldown    int64
	Ap          int64
	Range       int64
	Damage      sql.NullInt64
	Healing     sql.NullInt64
}

type Unit struct {
	ID       int64
	Name     string
	Skills   sql.NullString
	Movement sql.NullString
	Maxhp    sql.NullInt64
	Ap       sql.NullInt64
	Speed    sql.NullInt64
	Armies   sql.NullString
}

type UnitsSkill struct {
	Unitid  int64
	Skillid int64
}

type User struct {
	ID           int64
	Username     string
	PasswordHash sql.NullString
	Steamid      sql.NullString
	Lastloggedin sql.NullTime
	Avatar       sql.NullString
}

type UsersArmy struct {
	Userid int64
	Armyid int64
}
