package main

import (
	"fmt"
	"log"
	"net/http"
	"server/internal"
	"server/internal/server"
	"server/internal/server/clients"
)

func main() {
	// Define the game hub
	hub := server.NewHub()

	// define the handler for the websocket connections
	http.HandleFunc("/ws", func(w http.ResponseWriter, r *http.Request) {
		hub.Serve(clients.NewWebSocketClient, w, r)
	})
	go hub.Run()
	addr := fmt.Sprintf(":%d", internal.WSport)

	log.Printf("Server started on %s", addr)

	// WARNING: this is not secure, the certificate and key are generated by me and should be changed before full launch
	err := http.ListenAndServeTLS(addr, "server/cert/server.crt", "server/cert/server.key", nil)
	if err != nil {
		log.Fatalf("Failed to start server: %v", err)
	}
}
