syntax = "proto3";

package packets;
option go_package = "pkg/packets";

enum ChatType { Nothing = 0; Global = 1; Local = 2; Party = 3; Max = 4; }
enum Speeds { Normal = 0; Slow = 1; Fast = 2;}

message Vector3Msg { float x = 1; float y = 2; float z = 3; }
message Vector2Msg { float x = 1; float y = 2; }
message Vector2IMsg { int32 x = 1; int32 y = 2; }

// Game Data
message FactionData { int64 id = 1; string name = 2; string description = 3; repeated int64 armyIds = 4; }
message ArmyData { int64 id = 1; string name = 2; string description = 3; repeated UnitArmyData unitIds = 4; }
message UnitArmyData { int64 unitId = 1; int32 count = 2; }
message UnitData { int64 id = 1; string name = 2; string attacks = 3; string movement = 4; int64 maxHP = 5; int64 AP = 6; Speeds Speed = 7; int64 factionId = 8; }


message ChatMessage { ChatType type = 1; string msg = 2; string Username = 3;}
message IdMessage { uint64 id = 1; }
message LoginRequestMessage { string username = 1; string password = 2; }
message SteamAuthTicketMessage { string steamUsername = 1; bytes ticket = 2;}
message RegisterRequestMessage { string username = 1; string password = 2; }
message OkResponseMessage { }
message DenyResponseMessage { string reason = 1; }
message CommandMessage { string command = 1; repeated string args = 2; }
message ChangeStateMessage { string stateName = 1; }
message QueueMessage { string QueueType = 1; }
message HexPositionMessage { Vector2Msg position = 1; }
message HexPositionsMessage { int32 id = 1; repeated HexPositionMessage positions = 2;}
message OpponentMessage { string id = 1; bool steam = 2; string AvatarImage = 3; }
message StartGameMessage {}
message SeedMessage { repeated int32 seed = 1; }
message IDsMessage { repeated IdMessage IDs = 1; }
message UnitMessage { uint64 OwnerId = 1; int32 UnitId = 2; int64 AP = 5; int64 HP = 6; int64 MaxHP = 7; Speeds speed = 8; string UnitName = 9; Vector3Msg Pos = 10;}
message UnitPositionMessage { int32 unitId = 1; Vector2IMsg Position = 2; }
message UnitPositionsMessage { repeated UnitPositionMessage units = 1; }
message GameDataMessage { GameDataVersion version = 1; repeated FactionData factions = 2; repeated ArmyData armies = 3; repeated UnitData units = 4; }
message GameDataVersion { string Version = 1; }
message ArmyIDMessage { int64 Id = 1; }
message UnitIDsMessage { repeated UnitIDMessage ids = 1; }
message UnitIDMessage {int64 Id = 1; int32 unitId = 2;}
// more message types here


// protoc -I="shared" --go_out="server" "shared/packets.proto"
// protoc -I="shared" --csharp_out="Client" "shared/packets.proto"

message Packet {
  uint64 sender_id = 1;
  oneof msg {
    ChatMessage chat = 2;
    IdMessage id = 3;
    LoginRequestMessage loginRequest = 4;
    RegisterRequestMessage registerRequest = 5;
    OkResponseMessage OK = 6;
    DenyResponseMessage Deny = 7;
    CommandMessage command = 8;
    HexPositionMessage hexPosition = 9;
    HexPositionsMessage hexPositions = 10;
    SteamAuthTicketMessage steamTicket = 11;
    ChangeStateMessage changeState = 12;
    QueueMessage queue = 13;
    OpponentMessage opponent = 14;
    StartGameMessage startGame = 15;
    SeedMessage seed = 16;
    IDsMessage IDs = 17;
    UnitMessage Unit = 18;
    GameDataMessage GameData = 19;
    GameDataVersion GameVersion = 20;
    ArmyIDMessage ArmyId = 21;
    UnitPositionMessage UnitPosition = 22;
    UnitPositionsMessage UnitPositions = 23;
    UnitIDsMessage UnitIds = 24;
    //...
  }
}
