// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: packets.proto

package packets

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatType int32

const (
	ChatType_Nothing ChatType = 0
	ChatType_Global  ChatType = 1
	ChatType_Local   ChatType = 2
	ChatType_Party   ChatType = 3
	ChatType_Max     ChatType = 4
)

// Enum value maps for ChatType.
var (
	ChatType_name = map[int32]string{
		0: "Nothing",
		1: "Global",
		2: "Local",
		3: "Party",
		4: "Max",
	}
	ChatType_value = map[string]int32{
		"Nothing": 0,
		"Global":  1,
		"Local":   2,
		"Party":   3,
		"Max":     4,
	}
)

func (x ChatType) Enum() *ChatType {
	p := new(ChatType)
	*p = x
	return p
}

func (x ChatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatType) Descriptor() protoreflect.EnumDescriptor {
	return file_packets_proto_enumTypes[0].Descriptor()
}

func (ChatType) Type() protoreflect.EnumType {
	return &file_packets_proto_enumTypes[0]
}

func (x ChatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatType.Descriptor instead.
func (ChatType) EnumDescriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{0}
}

type Vector3Msg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector3Msg) Reset() {
	*x = Vector3Msg{}
	mi := &file_packets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector3Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector3Msg) ProtoMessage() {}

func (x *Vector3Msg) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector3Msg.ProtoReflect.Descriptor instead.
func (*Vector3Msg) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{0}
}

func (x *Vector3Msg) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector3Msg) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vector3Msg) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ChatType               `protobuf:"varint,1,opt,name=type,proto3,enum=packets.ChatType" json:"type,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=Username,proto3" json:"Username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_packets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{1}
}

func (x *ChatMessage) GetType() ChatType {
	if x != nil {
		return x.Type
	}
	return ChatType_Nothing
}

func (x *ChatMessage) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ChatMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type IdMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdMessage) Reset() {
	*x = IdMessage{}
	mi := &file_packets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdMessage) ProtoMessage() {}

func (x *IdMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdMessage.ProtoReflect.Descriptor instead.
func (*IdMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{2}
}

func (x *IdMessage) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type LoginRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequestMessage) Reset() {
	*x = LoginRequestMessage{}
	mi := &file_packets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequestMessage) ProtoMessage() {}

func (x *LoginRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequestMessage.ProtoReflect.Descriptor instead.
func (*LoginRequestMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{3}
}

func (x *LoginRequestMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequestMessage) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequestMessage) Reset() {
	*x = RegisterRequestMessage{}
	mi := &file_packets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequestMessage) ProtoMessage() {}

func (x *RegisterRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequestMessage.ProtoReflect.Descriptor instead.
func (*RegisterRequestMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterRequestMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequestMessage) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type OkResponseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OkResponseMessage) Reset() {
	*x = OkResponseMessage{}
	mi := &file_packets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OkResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OkResponseMessage) ProtoMessage() {}

func (x *OkResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OkResponseMessage.ProtoReflect.Descriptor instead.
func (*OkResponseMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{5}
}

type DenyResponseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DenyResponseMessage) Reset() {
	*x = DenyResponseMessage{}
	mi := &file_packets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenyResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenyResponseMessage) ProtoMessage() {}

func (x *DenyResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenyResponseMessage.ProtoReflect.Descriptor instead.
func (*DenyResponseMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{6}
}

func (x *DenyResponseMessage) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CommandMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandMessage) Reset() {
	*x = CommandMessage{}
	mi := &file_packets_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandMessage) ProtoMessage() {}

func (x *CommandMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandMessage.ProtoReflect.Descriptor instead.
func (*CommandMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{7}
}

func (x *CommandMessage) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CommandMessage) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type Packet struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	SenderId uint64                 `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	// Types that are valid to be assigned to Msg:
	//
	//	*Packet_Chat
	//	*Packet_Id
	//	*Packet_LoginRequest
	//	*Packet_RegisterRequest
	//	*Packet_OK
	//	*Packet_Deny
	//	*Packet_Command
	Msg           isPacket_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_packets_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{8}
}

func (x *Packet) GetSenderId() uint64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *Packet) GetMsg() isPacket_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Packet) GetChat() *ChatMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

func (x *Packet) GetId() *IdMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_Id); ok {
			return x.Id
		}
	}
	return nil
}

func (x *Packet) GetLoginRequest() *LoginRequestMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_LoginRequest); ok {
			return x.LoginRequest
		}
	}
	return nil
}

func (x *Packet) GetRegisterRequest() *RegisterRequestMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_RegisterRequest); ok {
			return x.RegisterRequest
		}
	}
	return nil
}

func (x *Packet) GetOK() *OkResponseMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_OK); ok {
			return x.OK
		}
	}
	return nil
}

func (x *Packet) GetDeny() *DenyResponseMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_Deny); ok {
			return x.Deny
		}
	}
	return nil
}

func (x *Packet) GetCommand() *CommandMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_Command); ok {
			return x.Command
		}
	}
	return nil
}

type isPacket_Msg interface {
	isPacket_Msg()
}

type Packet_Chat struct {
	Chat *ChatMessage `protobuf:"bytes,2,opt,name=chat,proto3,oneof"`
}

type Packet_Id struct {
	Id *IdMessage `protobuf:"bytes,3,opt,name=id,proto3,oneof"`
}

type Packet_LoginRequest struct {
	LoginRequest *LoginRequestMessage `protobuf:"bytes,4,opt,name=loginRequest,proto3,oneof"`
}

type Packet_RegisterRequest struct {
	RegisterRequest *RegisterRequestMessage `protobuf:"bytes,5,opt,name=registerRequest,proto3,oneof"`
}

type Packet_OK struct {
	OK *OkResponseMessage `protobuf:"bytes,6,opt,name=OK,proto3,oneof"`
}

type Packet_Deny struct {
	Deny *DenyResponseMessage `protobuf:"bytes,7,opt,name=Deny,proto3,oneof"`
}

type Packet_Command struct {
	Command *CommandMessage `protobuf:"bytes,12,opt,name=command,proto3,oneof"` //...
}

func (*Packet_Chat) isPacket_Msg() {}

func (*Packet_Id) isPacket_Msg() {}

func (*Packet_LoginRequest) isPacket_Msg() {}

func (*Packet_RegisterRequest) isPacket_Msg() {}

func (*Packet_OK) isPacket_Msg() {}

func (*Packet_Deny) isPacket_Msg() {}

func (*Packet_Command) isPacket_Msg() {}

var File_packets_proto protoreflect.FileDescriptor

const file_packets_proto_rawDesc = "" +
	"\n" +
	"\rpackets.proto\x12\apackets\"6\n" +
	"\n" +
	"Vector3Msg\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01z\"b\n" +
	"\vChatMessage\x12%\n" +
	"\x04type\x18\x01 \x01(\x0e2\x11.packets.ChatTypeR\x04type\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1a\n" +
	"\bUsername\x18\x03 \x01(\tR\bUsername\"\x1b\n" +
	"\tIdMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"M\n" +
	"\x13LoginRequestMessage\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"P\n" +
	"\x16RegisterRequestMessage\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x13\n" +
	"\x11OkResponseMessage\"-\n" +
	"\x13DenyResponseMessage\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\">\n" +
	"\x0eCommandMessage\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\"\xa6\x03\n" +
	"\x06Packet\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x04R\bsenderId\x12*\n" +
	"\x04chat\x18\x02 \x01(\v2\x14.packets.ChatMessageH\x00R\x04chat\x12$\n" +
	"\x02id\x18\x03 \x01(\v2\x12.packets.IdMessageH\x00R\x02id\x12B\n" +
	"\floginRequest\x18\x04 \x01(\v2\x1c.packets.LoginRequestMessageH\x00R\floginRequest\x12K\n" +
	"\x0fregisterRequest\x18\x05 \x01(\v2\x1f.packets.RegisterRequestMessageH\x00R\x0fregisterRequest\x12,\n" +
	"\x02OK\x18\x06 \x01(\v2\x1a.packets.OkResponseMessageH\x00R\x02OK\x122\n" +
	"\x04Deny\x18\a \x01(\v2\x1c.packets.DenyResponseMessageH\x00R\x04Deny\x123\n" +
	"\acommand\x18\f \x01(\v2\x17.packets.CommandMessageH\x00R\acommandB\x05\n" +
	"\x03msg*B\n" +
	"\bChatType\x12\v\n" +
	"\aNothing\x10\x00\x12\n" +
	"\n" +
	"\x06Global\x10\x01\x12\t\n" +
	"\x05Local\x10\x02\x12\t\n" +
	"\x05Party\x10\x03\x12\a\n" +
	"\x03Max\x10\x04B\rZ\vpkg/packetsb\x06proto3"

var (
	file_packets_proto_rawDescOnce sync.Once
	file_packets_proto_rawDescData []byte
)

func file_packets_proto_rawDescGZIP() []byte {
	file_packets_proto_rawDescOnce.Do(func() {
		file_packets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packets_proto_rawDesc), len(file_packets_proto_rawDesc)))
	})
	return file_packets_proto_rawDescData
}

var file_packets_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_packets_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_packets_proto_goTypes = []any{
	(ChatType)(0),                  // 0: packets.ChatType
	(*Vector3Msg)(nil),             // 1: packets.Vector3Msg
	(*ChatMessage)(nil),            // 2: packets.ChatMessage
	(*IdMessage)(nil),              // 3: packets.IdMessage
	(*LoginRequestMessage)(nil),    // 4: packets.LoginRequestMessage
	(*RegisterRequestMessage)(nil), // 5: packets.RegisterRequestMessage
	(*OkResponseMessage)(nil),      // 6: packets.OkResponseMessage
	(*DenyResponseMessage)(nil),    // 7: packets.DenyResponseMessage
	(*CommandMessage)(nil),         // 8: packets.CommandMessage
	(*Packet)(nil),                 // 9: packets.Packet
}
var file_packets_proto_depIdxs = []int32{
	0, // 0: packets.ChatMessage.type:type_name -> packets.ChatType
	2, // 1: packets.Packet.chat:type_name -> packets.ChatMessage
	3, // 2: packets.Packet.id:type_name -> packets.IdMessage
	4, // 3: packets.Packet.loginRequest:type_name -> packets.LoginRequestMessage
	5, // 4: packets.Packet.registerRequest:type_name -> packets.RegisterRequestMessage
	6, // 5: packets.Packet.OK:type_name -> packets.OkResponseMessage
	7, // 6: packets.Packet.Deny:type_name -> packets.DenyResponseMessage
	8, // 7: packets.Packet.command:type_name -> packets.CommandMessage
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_packets_proto_init() }
func file_packets_proto_init() {
	if File_packets_proto != nil {
		return
	}
	file_packets_proto_msgTypes[8].OneofWrappers = []any{
		(*Packet_Chat)(nil),
		(*Packet_Id)(nil),
		(*Packet_LoginRequest)(nil),
		(*Packet_RegisterRequest)(nil),
		(*Packet_OK)(nil),
		(*Packet_Deny)(nil),
		(*Packet_Command)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packets_proto_rawDesc), len(file_packets_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packets_proto_goTypes,
		DependencyIndexes: file_packets_proto_depIdxs,
		EnumInfos:         file_packets_proto_enumTypes,
		MessageInfos:      file_packets_proto_msgTypes,
	}.Build()
	File_packets_proto = out.File
	file_packets_proto_goTypes = nil
	file_packets_proto_depIdxs = nil
}
