// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: packets.proto

package packets

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatType int32

const (
	ChatType_Nothing ChatType = 0
	ChatType_Global  ChatType = 1
	ChatType_Local   ChatType = 2
	ChatType_Party   ChatType = 3
	ChatType_Max     ChatType = 4
)

// Enum value maps for ChatType.
var (
	ChatType_name = map[int32]string{
		0: "Nothing",
		1: "Global",
		2: "Local",
		3: "Party",
		4: "Max",
	}
	ChatType_value = map[string]int32{
		"Nothing": 0,
		"Global":  1,
		"Local":   2,
		"Party":   3,
		"Max":     4,
	}
)

func (x ChatType) Enum() *ChatType {
	p := new(ChatType)
	*p = x
	return p
}

func (x ChatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatType) Descriptor() protoreflect.EnumDescriptor {
	return file_packets_proto_enumTypes[0].Descriptor()
}

func (ChatType) Type() protoreflect.EnumType {
	return &file_packets_proto_enumTypes[0]
}

func (x ChatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatType.Descriptor instead.
func (ChatType) EnumDescriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{0}
}

type Speeds int32

const (
	Speeds_Normal Speeds = 0
	Speeds_Slow   Speeds = 1
	Speeds_Fast   Speeds = 2
)

// Enum value maps for Speeds.
var (
	Speeds_name = map[int32]string{
		0: "Normal",
		1: "Slow",
		2: "Fast",
	}
	Speeds_value = map[string]int32{
		"Normal": 0,
		"Slow":   1,
		"Fast":   2,
	}
)

func (x Speeds) Enum() *Speeds {
	p := new(Speeds)
	*p = x
	return p
}

func (x Speeds) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Speeds) Descriptor() protoreflect.EnumDescriptor {
	return file_packets_proto_enumTypes[1].Descriptor()
}

func (Speeds) Type() protoreflect.EnumType {
	return &file_packets_proto_enumTypes[1]
}

func (x Speeds) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Speeds.Descriptor instead.
func (Speeds) EnumDescriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{1}
}

type Vector3Msg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector3Msg) Reset() {
	*x = Vector3Msg{}
	mi := &file_packets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector3Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector3Msg) ProtoMessage() {}

func (x *Vector3Msg) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector3Msg.ProtoReflect.Descriptor instead.
func (*Vector3Msg) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{0}
}

func (x *Vector3Msg) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector3Msg) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vector3Msg) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type Vector2Msg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector2Msg) Reset() {
	*x = Vector2Msg{}
	mi := &file_packets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector2Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector2Msg) ProtoMessage() {}

func (x *Vector2Msg) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector2Msg.ProtoReflect.Descriptor instead.
func (*Vector2Msg) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{1}
}

func (x *Vector2Msg) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector2Msg) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Vector2IMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector2IMsg) Reset() {
	*x = Vector2IMsg{}
	mi := &file_packets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector2IMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector2IMsg) ProtoMessage() {}

func (x *Vector2IMsg) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector2IMsg.ProtoReflect.Descriptor instead.
func (*Vector2IMsg) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{2}
}

func (x *Vector2IMsg) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector2IMsg) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// Game Data
type FactionData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ArmyIds       []int64                `protobuf:"varint,4,rep,packed,name=armyIds,proto3" json:"armyIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FactionData) Reset() {
	*x = FactionData{}
	mi := &file_packets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactionData) ProtoMessage() {}

func (x *FactionData) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactionData.ProtoReflect.Descriptor instead.
func (*FactionData) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{3}
}

func (x *FactionData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FactionData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FactionData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FactionData) GetArmyIds() []int64 {
	if x != nil {
		return x.ArmyIds
	}
	return nil
}

type ArmyData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	UnitIds       []*UnitArmyData        `protobuf:"bytes,4,rep,name=unitIds,proto3" json:"unitIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArmyData) Reset() {
	*x = ArmyData{}
	mi := &file_packets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArmyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArmyData) ProtoMessage() {}

func (x *ArmyData) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArmyData.ProtoReflect.Descriptor instead.
func (*ArmyData) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{4}
}

func (x *ArmyData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ArmyData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ArmyData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ArmyData) GetUnitIds() []*UnitArmyData {
	if x != nil {
		return x.UnitIds
	}
	return nil
}

type UnitArmyData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnitId        int64                  `protobuf:"varint,1,opt,name=unitId,proto3" json:"unitId,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnitArmyData) Reset() {
	*x = UnitArmyData{}
	mi := &file_packets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnitArmyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitArmyData) ProtoMessage() {}

func (x *UnitArmyData) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitArmyData.ProtoReflect.Descriptor instead.
func (*UnitArmyData) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{5}
}

func (x *UnitArmyData) GetUnitId() int64 {
	if x != nil {
		return x.UnitId
	}
	return 0
}

func (x *UnitArmyData) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type UnitData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Attacks       string                 `protobuf:"bytes,3,opt,name=attacks,proto3" json:"attacks,omitempty"`
	Movement      string                 `protobuf:"bytes,4,opt,name=movement,proto3" json:"movement,omitempty"`
	MaxHP         int64                  `protobuf:"varint,5,opt,name=maxHP,proto3" json:"maxHP,omitempty"`
	AP            int64                  `protobuf:"varint,6,opt,name=AP,proto3" json:"AP,omitempty"`
	Speed         Speeds                 `protobuf:"varint,7,opt,name=Speed,proto3,enum=packets.Speeds" json:"Speed,omitempty"`
	FactionId     int64                  `protobuf:"varint,8,opt,name=factionId,proto3" json:"factionId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnitData) Reset() {
	*x = UnitData{}
	mi := &file_packets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnitData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitData) ProtoMessage() {}

func (x *UnitData) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitData.ProtoReflect.Descriptor instead.
func (*UnitData) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{6}
}

func (x *UnitData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UnitData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UnitData) GetAttacks() string {
	if x != nil {
		return x.Attacks
	}
	return ""
}

func (x *UnitData) GetMovement() string {
	if x != nil {
		return x.Movement
	}
	return ""
}

func (x *UnitData) GetMaxHP() int64 {
	if x != nil {
		return x.MaxHP
	}
	return 0
}

func (x *UnitData) GetAP() int64 {
	if x != nil {
		return x.AP
	}
	return 0
}

func (x *UnitData) GetSpeed() Speeds {
	if x != nil {
		return x.Speed
	}
	return Speeds_Normal
}

func (x *UnitData) GetFactionId() int64 {
	if x != nil {
		return x.FactionId
	}
	return 0
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ChatType               `protobuf:"varint,1,opt,name=type,proto3,enum=packets.ChatType" json:"type,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=Username,proto3" json:"Username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_packets_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{7}
}

func (x *ChatMessage) GetType() ChatType {
	if x != nil {
		return x.Type
	}
	return ChatType_Nothing
}

func (x *ChatMessage) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ChatMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type IdMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdMessage) Reset() {
	*x = IdMessage{}
	mi := &file_packets_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdMessage) ProtoMessage() {}

func (x *IdMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdMessage.ProtoReflect.Descriptor instead.
func (*IdMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{8}
}

func (x *IdMessage) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type LoginRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequestMessage) Reset() {
	*x = LoginRequestMessage{}
	mi := &file_packets_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequestMessage) ProtoMessage() {}

func (x *LoginRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequestMessage.ProtoReflect.Descriptor instead.
func (*LoginRequestMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{9}
}

func (x *LoginRequestMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequestMessage) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SteamAuthTicketMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SteamUsername string                 `protobuf:"bytes,1,opt,name=steamUsername,proto3" json:"steamUsername,omitempty"`
	Ticket        []byte                 `protobuf:"bytes,2,opt,name=ticket,proto3" json:"ticket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SteamAuthTicketMessage) Reset() {
	*x = SteamAuthTicketMessage{}
	mi := &file_packets_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SteamAuthTicketMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SteamAuthTicketMessage) ProtoMessage() {}

func (x *SteamAuthTicketMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SteamAuthTicketMessage.ProtoReflect.Descriptor instead.
func (*SteamAuthTicketMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{10}
}

func (x *SteamAuthTicketMessage) GetSteamUsername() string {
	if x != nil {
		return x.SteamUsername
	}
	return ""
}

func (x *SteamAuthTicketMessage) GetTicket() []byte {
	if x != nil {
		return x.Ticket
	}
	return nil
}

type RegisterRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequestMessage) Reset() {
	*x = RegisterRequestMessage{}
	mi := &file_packets_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequestMessage) ProtoMessage() {}

func (x *RegisterRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequestMessage.ProtoReflect.Descriptor instead.
func (*RegisterRequestMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{11}
}

func (x *RegisterRequestMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequestMessage) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type OkResponseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OkResponseMessage) Reset() {
	*x = OkResponseMessage{}
	mi := &file_packets_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OkResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OkResponseMessage) ProtoMessage() {}

func (x *OkResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OkResponseMessage.ProtoReflect.Descriptor instead.
func (*OkResponseMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{12}
}

type DenyResponseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DenyResponseMessage) Reset() {
	*x = DenyResponseMessage{}
	mi := &file_packets_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenyResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenyResponseMessage) ProtoMessage() {}

func (x *DenyResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenyResponseMessage.ProtoReflect.Descriptor instead.
func (*DenyResponseMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{13}
}

func (x *DenyResponseMessage) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CommandMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandMessage) Reset() {
	*x = CommandMessage{}
	mi := &file_packets_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandMessage) ProtoMessage() {}

func (x *CommandMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandMessage.ProtoReflect.Descriptor instead.
func (*CommandMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{14}
}

func (x *CommandMessage) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CommandMessage) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type ChangeStateMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StateName     string                 `protobuf:"bytes,1,opt,name=stateName,proto3" json:"stateName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeStateMessage) Reset() {
	*x = ChangeStateMessage{}
	mi := &file_packets_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeStateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeStateMessage) ProtoMessage() {}

func (x *ChangeStateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeStateMessage.ProtoReflect.Descriptor instead.
func (*ChangeStateMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{15}
}

func (x *ChangeStateMessage) GetStateName() string {
	if x != nil {
		return x.StateName
	}
	return ""
}

type QueueMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueType     string                 `protobuf:"bytes,1,opt,name=QueueType,proto3" json:"QueueType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueMessage) Reset() {
	*x = QueueMessage{}
	mi := &file_packets_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueMessage) ProtoMessage() {}

func (x *QueueMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueMessage.ProtoReflect.Descriptor instead.
func (*QueueMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{16}
}

func (x *QueueMessage) GetQueueType() string {
	if x != nil {
		return x.QueueType
	}
	return ""
}

type HexPositionMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *Vector2Msg            `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HexPositionMessage) Reset() {
	*x = HexPositionMessage{}
	mi := &file_packets_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HexPositionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HexPositionMessage) ProtoMessage() {}

func (x *HexPositionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HexPositionMessage.ProtoReflect.Descriptor instead.
func (*HexPositionMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{17}
}

func (x *HexPositionMessage) GetPosition() *Vector2Msg {
	if x != nil {
		return x.Position
	}
	return nil
}

type HexPositionsMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Positions     []*HexPositionMessage  `protobuf:"bytes,2,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HexPositionsMessage) Reset() {
	*x = HexPositionsMessage{}
	mi := &file_packets_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HexPositionsMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HexPositionsMessage) ProtoMessage() {}

func (x *HexPositionsMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HexPositionsMessage.ProtoReflect.Descriptor instead.
func (*HexPositionsMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{18}
}

func (x *HexPositionsMessage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HexPositionsMessage) GetPositions() []*HexPositionMessage {
	if x != nil {
		return x.Positions
	}
	return nil
}

type OpponentMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Steam         bool                   `protobuf:"varint,2,opt,name=steam,proto3" json:"steam,omitempty"`
	AvatarImage   string                 `protobuf:"bytes,3,opt,name=AvatarImage,proto3" json:"AvatarImage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpponentMessage) Reset() {
	*x = OpponentMessage{}
	mi := &file_packets_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpponentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpponentMessage) ProtoMessage() {}

func (x *OpponentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpponentMessage.ProtoReflect.Descriptor instead.
func (*OpponentMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{19}
}

func (x *OpponentMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OpponentMessage) GetSteam() bool {
	if x != nil {
		return x.Steam
	}
	return false
}

func (x *OpponentMessage) GetAvatarImage() string {
	if x != nil {
		return x.AvatarImage
	}
	return ""
}

type StartGameMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGameMessage) Reset() {
	*x = StartGameMessage{}
	mi := &file_packets_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGameMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameMessage) ProtoMessage() {}

func (x *StartGameMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameMessage.ProtoReflect.Descriptor instead.
func (*StartGameMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{20}
}

type SeedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seed          []int32                `protobuf:"varint,1,rep,packed,name=seed,proto3" json:"seed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeedMessage) Reset() {
	*x = SeedMessage{}
	mi := &file_packets_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeedMessage) ProtoMessage() {}

func (x *SeedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeedMessage.ProtoReflect.Descriptor instead.
func (*SeedMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{21}
}

func (x *SeedMessage) GetSeed() []int32 {
	if x != nil {
		return x.Seed
	}
	return nil
}

type IDsMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IDs           []*IdMessage           `protobuf:"bytes,1,rep,name=IDs,proto3" json:"IDs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDsMessage) Reset() {
	*x = IDsMessage{}
	mi := &file_packets_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDsMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDsMessage) ProtoMessage() {}

func (x *IDsMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDsMessage.ProtoReflect.Descriptor instead.
func (*IDsMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{22}
}

func (x *IDsMessage) GetIDs() []*IdMessage {
	if x != nil {
		return x.IDs
	}
	return nil
}

type UnitMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       uint64                 `protobuf:"varint,1,opt,name=OwnerId,proto3" json:"OwnerId,omitempty"`
	UnitId        int32                  `protobuf:"varint,2,opt,name=UnitId,proto3" json:"UnitId,omitempty"`
	AP            int64                  `protobuf:"varint,5,opt,name=AP,proto3" json:"AP,omitempty"`
	HP            int64                  `protobuf:"varint,6,opt,name=HP,proto3" json:"HP,omitempty"`
	MaxHP         int64                  `protobuf:"varint,7,opt,name=MaxHP,proto3" json:"MaxHP,omitempty"`
	Speed         Speeds                 `protobuf:"varint,8,opt,name=speed,proto3,enum=packets.Speeds" json:"speed,omitempty"`
	UnitName      string                 `protobuf:"bytes,9,opt,name=UnitName,proto3" json:"UnitName,omitempty"`
	Pos           *Vector3Msg            `protobuf:"bytes,10,opt,name=Pos,proto3" json:"Pos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnitMessage) Reset() {
	*x = UnitMessage{}
	mi := &file_packets_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnitMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitMessage) ProtoMessage() {}

func (x *UnitMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitMessage.ProtoReflect.Descriptor instead.
func (*UnitMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{23}
}

func (x *UnitMessage) GetOwnerId() uint64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *UnitMessage) GetUnitId() int32 {
	if x != nil {
		return x.UnitId
	}
	return 0
}

func (x *UnitMessage) GetAP() int64 {
	if x != nil {
		return x.AP
	}
	return 0
}

func (x *UnitMessage) GetHP() int64 {
	if x != nil {
		return x.HP
	}
	return 0
}

func (x *UnitMessage) GetMaxHP() int64 {
	if x != nil {
		return x.MaxHP
	}
	return 0
}

func (x *UnitMessage) GetSpeed() Speeds {
	if x != nil {
		return x.Speed
	}
	return Speeds_Normal
}

func (x *UnitMessage) GetUnitName() string {
	if x != nil {
		return x.UnitName
	}
	return ""
}

func (x *UnitMessage) GetPos() *Vector3Msg {
	if x != nil {
		return x.Pos
	}
	return nil
}

type UnitPositionMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnitId        int32                  `protobuf:"varint,1,opt,name=unitId,proto3" json:"unitId,omitempty"`
	Position      *Vector2IMsg           `protobuf:"bytes,2,opt,name=Position,proto3" json:"Position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnitPositionMessage) Reset() {
	*x = UnitPositionMessage{}
	mi := &file_packets_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnitPositionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitPositionMessage) ProtoMessage() {}

func (x *UnitPositionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitPositionMessage.ProtoReflect.Descriptor instead.
func (*UnitPositionMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{24}
}

func (x *UnitPositionMessage) GetUnitId() int32 {
	if x != nil {
		return x.UnitId
	}
	return 0
}

func (x *UnitPositionMessage) GetPosition() *Vector2IMsg {
	if x != nil {
		return x.Position
	}
	return nil
}

type UnitPositionsMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Units         []*UnitPositionMessage `protobuf:"bytes,1,rep,name=units,proto3" json:"units,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnitPositionsMessage) Reset() {
	*x = UnitPositionsMessage{}
	mi := &file_packets_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnitPositionsMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitPositionsMessage) ProtoMessage() {}

func (x *UnitPositionsMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitPositionsMessage.ProtoReflect.Descriptor instead.
func (*UnitPositionsMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{25}
}

func (x *UnitPositionsMessage) GetUnits() []*UnitPositionMessage {
	if x != nil {
		return x.Units
	}
	return nil
}

type GameDataMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       *GameDataVersion       `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Factions      []*FactionData         `protobuf:"bytes,2,rep,name=factions,proto3" json:"factions,omitempty"`
	Armies        []*ArmyData            `protobuf:"bytes,3,rep,name=armies,proto3" json:"armies,omitempty"`
	Units         []*UnitData            `protobuf:"bytes,4,rep,name=units,proto3" json:"units,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameDataMessage) Reset() {
	*x = GameDataMessage{}
	mi := &file_packets_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameDataMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameDataMessage) ProtoMessage() {}

func (x *GameDataMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameDataMessage.ProtoReflect.Descriptor instead.
func (*GameDataMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{26}
}

func (x *GameDataMessage) GetVersion() *GameDataVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *GameDataMessage) GetFactions() []*FactionData {
	if x != nil {
		return x.Factions
	}
	return nil
}

func (x *GameDataMessage) GetArmies() []*ArmyData {
	if x != nil {
		return x.Armies
	}
	return nil
}

func (x *GameDataMessage) GetUnits() []*UnitData {
	if x != nil {
		return x.Units
	}
	return nil
}

type GameDataVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=Version,proto3" json:"Version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameDataVersion) Reset() {
	*x = GameDataVersion{}
	mi := &file_packets_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameDataVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameDataVersion) ProtoMessage() {}

func (x *GameDataVersion) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameDataVersion.ProtoReflect.Descriptor instead.
func (*GameDataVersion) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{27}
}

func (x *GameDataVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ArmyIDMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArmyIDMessage) Reset() {
	*x = ArmyIDMessage{}
	mi := &file_packets_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArmyIDMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArmyIDMessage) ProtoMessage() {}

func (x *ArmyIDMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArmyIDMessage.ProtoReflect.Descriptor instead.
func (*ArmyIDMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{28}
}

func (x *ArmyIDMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UnitIDsMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []*UnitIDMessage       `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnitIDsMessage) Reset() {
	*x = UnitIDsMessage{}
	mi := &file_packets_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnitIDsMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitIDsMessage) ProtoMessage() {}

func (x *UnitIDsMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitIDsMessage.ProtoReflect.Descriptor instead.
func (*UnitIDsMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{29}
}

func (x *UnitIDsMessage) GetIds() []*UnitIDMessage {
	if x != nil {
		return x.Ids
	}
	return nil
}

type UnitIDMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	UnitId        int32                  `protobuf:"varint,2,opt,name=unitId,proto3" json:"unitId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnitIDMessage) Reset() {
	*x = UnitIDMessage{}
	mi := &file_packets_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnitIDMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitIDMessage) ProtoMessage() {}

func (x *UnitIDMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitIDMessage.ProtoReflect.Descriptor instead.
func (*UnitIDMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{30}
}

func (x *UnitIDMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UnitIDMessage) GetUnitId() int32 {
	if x != nil {
		return x.UnitId
	}
	return 0
}

type Packet struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	SenderId uint64                 `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	// Types that are valid to be assigned to Msg:
	//
	//	*Packet_Chat
	//	*Packet_Id
	//	*Packet_LoginRequest
	//	*Packet_RegisterRequest
	//	*Packet_OK
	//	*Packet_Deny
	//	*Packet_Command
	//	*Packet_HexPosition
	//	*Packet_HexPositions
	//	*Packet_SteamTicket
	//	*Packet_ChangeState
	//	*Packet_Queue
	//	*Packet_Opponent
	//	*Packet_StartGame
	//	*Packet_Seed
	//	*Packet_IDs
	//	*Packet_Unit
	//	*Packet_GameData
	//	*Packet_GameVersion
	//	*Packet_ArmyId
	//	*Packet_UnitPosition
	//	*Packet_UnitPositions
	//	*Packet_UnitIds
	Msg           isPacket_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_packets_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{31}
}

func (x *Packet) GetSenderId() uint64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *Packet) GetMsg() isPacket_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Packet) GetChat() *ChatMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

func (x *Packet) GetId() *IdMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_Id); ok {
			return x.Id
		}
	}
	return nil
}

func (x *Packet) GetLoginRequest() *LoginRequestMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_LoginRequest); ok {
			return x.LoginRequest
		}
	}
	return nil
}

func (x *Packet) GetRegisterRequest() *RegisterRequestMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_RegisterRequest); ok {
			return x.RegisterRequest
		}
	}
	return nil
}

func (x *Packet) GetOK() *OkResponseMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_OK); ok {
			return x.OK
		}
	}
	return nil
}

func (x *Packet) GetDeny() *DenyResponseMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_Deny); ok {
			return x.Deny
		}
	}
	return nil
}

func (x *Packet) GetCommand() *CommandMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *Packet) GetHexPosition() *HexPositionMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_HexPosition); ok {
			return x.HexPosition
		}
	}
	return nil
}

func (x *Packet) GetHexPositions() *HexPositionsMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_HexPositions); ok {
			return x.HexPositions
		}
	}
	return nil
}

func (x *Packet) GetSteamTicket() *SteamAuthTicketMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_SteamTicket); ok {
			return x.SteamTicket
		}
	}
	return nil
}

func (x *Packet) GetChangeState() *ChangeStateMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_ChangeState); ok {
			return x.ChangeState
		}
	}
	return nil
}

func (x *Packet) GetQueue() *QueueMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_Queue); ok {
			return x.Queue
		}
	}
	return nil
}

func (x *Packet) GetOpponent() *OpponentMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_Opponent); ok {
			return x.Opponent
		}
	}
	return nil
}

func (x *Packet) GetStartGame() *StartGameMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_StartGame); ok {
			return x.StartGame
		}
	}
	return nil
}

func (x *Packet) GetSeed() *SeedMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_Seed); ok {
			return x.Seed
		}
	}
	return nil
}

func (x *Packet) GetIDs() *IDsMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_IDs); ok {
			return x.IDs
		}
	}
	return nil
}

func (x *Packet) GetUnit() *UnitMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_Unit); ok {
			return x.Unit
		}
	}
	return nil
}

func (x *Packet) GetGameData() *GameDataMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_GameData); ok {
			return x.GameData
		}
	}
	return nil
}

func (x *Packet) GetGameVersion() *GameDataVersion {
	if x != nil {
		if x, ok := x.Msg.(*Packet_GameVersion); ok {
			return x.GameVersion
		}
	}
	return nil
}

func (x *Packet) GetArmyId() *ArmyIDMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_ArmyId); ok {
			return x.ArmyId
		}
	}
	return nil
}

func (x *Packet) GetUnitPosition() *UnitPositionMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_UnitPosition); ok {
			return x.UnitPosition
		}
	}
	return nil
}

func (x *Packet) GetUnitPositions() *UnitPositionsMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_UnitPositions); ok {
			return x.UnitPositions
		}
	}
	return nil
}

func (x *Packet) GetUnitIds() *UnitIDsMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_UnitIds); ok {
			return x.UnitIds
		}
	}
	return nil
}

type isPacket_Msg interface {
	isPacket_Msg()
}

type Packet_Chat struct {
	Chat *ChatMessage `protobuf:"bytes,2,opt,name=chat,proto3,oneof"`
}

type Packet_Id struct {
	Id *IdMessage `protobuf:"bytes,3,opt,name=id,proto3,oneof"`
}

type Packet_LoginRequest struct {
	LoginRequest *LoginRequestMessage `protobuf:"bytes,4,opt,name=loginRequest,proto3,oneof"`
}

type Packet_RegisterRequest struct {
	RegisterRequest *RegisterRequestMessage `protobuf:"bytes,5,opt,name=registerRequest,proto3,oneof"`
}

type Packet_OK struct {
	OK *OkResponseMessage `protobuf:"bytes,6,opt,name=OK,proto3,oneof"`
}

type Packet_Deny struct {
	Deny *DenyResponseMessage `protobuf:"bytes,7,opt,name=Deny,proto3,oneof"`
}

type Packet_Command struct {
	Command *CommandMessage `protobuf:"bytes,8,opt,name=command,proto3,oneof"`
}

type Packet_HexPosition struct {
	HexPosition *HexPositionMessage `protobuf:"bytes,9,opt,name=hexPosition,proto3,oneof"`
}

type Packet_HexPositions struct {
	HexPositions *HexPositionsMessage `protobuf:"bytes,10,opt,name=hexPositions,proto3,oneof"`
}

type Packet_SteamTicket struct {
	SteamTicket *SteamAuthTicketMessage `protobuf:"bytes,11,opt,name=steamTicket,proto3,oneof"`
}

type Packet_ChangeState struct {
	ChangeState *ChangeStateMessage `protobuf:"bytes,12,opt,name=changeState,proto3,oneof"`
}

type Packet_Queue struct {
	Queue *QueueMessage `protobuf:"bytes,13,opt,name=queue,proto3,oneof"`
}

type Packet_Opponent struct {
	Opponent *OpponentMessage `protobuf:"bytes,14,opt,name=opponent,proto3,oneof"`
}

type Packet_StartGame struct {
	StartGame *StartGameMessage `protobuf:"bytes,15,opt,name=startGame,proto3,oneof"`
}

type Packet_Seed struct {
	Seed *SeedMessage `protobuf:"bytes,16,opt,name=seed,proto3,oneof"`
}

type Packet_IDs struct {
	IDs *IDsMessage `protobuf:"bytes,17,opt,name=IDs,proto3,oneof"`
}

type Packet_Unit struct {
	Unit *UnitMessage `protobuf:"bytes,18,opt,name=Unit,proto3,oneof"`
}

type Packet_GameData struct {
	GameData *GameDataMessage `protobuf:"bytes,19,opt,name=GameData,proto3,oneof"`
}

type Packet_GameVersion struct {
	GameVersion *GameDataVersion `protobuf:"bytes,20,opt,name=GameVersion,proto3,oneof"`
}

type Packet_ArmyId struct {
	ArmyId *ArmyIDMessage `protobuf:"bytes,21,opt,name=ArmyId,proto3,oneof"`
}

type Packet_UnitPosition struct {
	UnitPosition *UnitPositionMessage `protobuf:"bytes,22,opt,name=UnitPosition,proto3,oneof"`
}

type Packet_UnitPositions struct {
	UnitPositions *UnitPositionsMessage `protobuf:"bytes,23,opt,name=UnitPositions,proto3,oneof"`
}

type Packet_UnitIds struct {
	UnitIds *UnitIDsMessage `protobuf:"bytes,24,opt,name=UnitIds,proto3,oneof"` //...
}

func (*Packet_Chat) isPacket_Msg() {}

func (*Packet_Id) isPacket_Msg() {}

func (*Packet_LoginRequest) isPacket_Msg() {}

func (*Packet_RegisterRequest) isPacket_Msg() {}

func (*Packet_OK) isPacket_Msg() {}

func (*Packet_Deny) isPacket_Msg() {}

func (*Packet_Command) isPacket_Msg() {}

func (*Packet_HexPosition) isPacket_Msg() {}

func (*Packet_HexPositions) isPacket_Msg() {}

func (*Packet_SteamTicket) isPacket_Msg() {}

func (*Packet_ChangeState) isPacket_Msg() {}

func (*Packet_Queue) isPacket_Msg() {}

func (*Packet_Opponent) isPacket_Msg() {}

func (*Packet_StartGame) isPacket_Msg() {}

func (*Packet_Seed) isPacket_Msg() {}

func (*Packet_IDs) isPacket_Msg() {}

func (*Packet_Unit) isPacket_Msg() {}

func (*Packet_GameData) isPacket_Msg() {}

func (*Packet_GameVersion) isPacket_Msg() {}

func (*Packet_ArmyId) isPacket_Msg() {}

func (*Packet_UnitPosition) isPacket_Msg() {}

func (*Packet_UnitPositions) isPacket_Msg() {}

func (*Packet_UnitIds) isPacket_Msg() {}

var File_packets_proto protoreflect.FileDescriptor

const file_packets_proto_rawDesc = "" +
	"\n" +
	"\rpackets.proto\x12\apackets\"6\n" +
	"\n" +
	"Vector3Msg\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01z\"(\n" +
	"\n" +
	"Vector2Msg\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\")\n" +
	"\vVector2IMsg\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"m\n" +
	"\vFactionData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aarmyIds\x18\x04 \x03(\x03R\aarmyIds\"\x81\x01\n" +
	"\bArmyData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12/\n" +
	"\aunitIds\x18\x04 \x03(\v2\x15.packets.UnitArmyDataR\aunitIds\"<\n" +
	"\fUnitArmyData\x12\x16\n" +
	"\x06unitId\x18\x01 \x01(\x03R\x06unitId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\xcf\x01\n" +
	"\bUnitData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aattacks\x18\x03 \x01(\tR\aattacks\x12\x1a\n" +
	"\bmovement\x18\x04 \x01(\tR\bmovement\x12\x14\n" +
	"\x05maxHP\x18\x05 \x01(\x03R\x05maxHP\x12\x0e\n" +
	"\x02AP\x18\x06 \x01(\x03R\x02AP\x12%\n" +
	"\x05Speed\x18\a \x01(\x0e2\x0f.packets.SpeedsR\x05Speed\x12\x1c\n" +
	"\tfactionId\x18\b \x01(\x03R\tfactionId\"b\n" +
	"\vChatMessage\x12%\n" +
	"\x04type\x18\x01 \x01(\x0e2\x11.packets.ChatTypeR\x04type\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1a\n" +
	"\bUsername\x18\x03 \x01(\tR\bUsername\"\x1b\n" +
	"\tIdMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"M\n" +
	"\x13LoginRequestMessage\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"V\n" +
	"\x16SteamAuthTicketMessage\x12$\n" +
	"\rsteamUsername\x18\x01 \x01(\tR\rsteamUsername\x12\x16\n" +
	"\x06ticket\x18\x02 \x01(\fR\x06ticket\"P\n" +
	"\x16RegisterRequestMessage\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x13\n" +
	"\x11OkResponseMessage\"-\n" +
	"\x13DenyResponseMessage\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\">\n" +
	"\x0eCommandMessage\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\"2\n" +
	"\x12ChangeStateMessage\x12\x1c\n" +
	"\tstateName\x18\x01 \x01(\tR\tstateName\",\n" +
	"\fQueueMessage\x12\x1c\n" +
	"\tQueueType\x18\x01 \x01(\tR\tQueueType\"E\n" +
	"\x12HexPositionMessage\x12/\n" +
	"\bposition\x18\x01 \x01(\v2\x13.packets.Vector2MsgR\bposition\"`\n" +
	"\x13HexPositionsMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x129\n" +
	"\tpositions\x18\x02 \x03(\v2\x1b.packets.HexPositionMessageR\tpositions\"Y\n" +
	"\x0fOpponentMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05steam\x18\x02 \x01(\bR\x05steam\x12 \n" +
	"\vAvatarImage\x18\x03 \x01(\tR\vAvatarImage\"\x12\n" +
	"\x10StartGameMessage\"!\n" +
	"\vSeedMessage\x12\x12\n" +
	"\x04seed\x18\x01 \x03(\x05R\x04seed\"2\n" +
	"\n" +
	"IDsMessage\x12$\n" +
	"\x03IDs\x18\x01 \x03(\v2\x12.packets.IdMessageR\x03IDs\"\xdf\x01\n" +
	"\vUnitMessage\x12\x18\n" +
	"\aOwnerId\x18\x01 \x01(\x04R\aOwnerId\x12\x16\n" +
	"\x06UnitId\x18\x02 \x01(\x05R\x06UnitId\x12\x0e\n" +
	"\x02AP\x18\x05 \x01(\x03R\x02AP\x12\x0e\n" +
	"\x02HP\x18\x06 \x01(\x03R\x02HP\x12\x14\n" +
	"\x05MaxHP\x18\a \x01(\x03R\x05MaxHP\x12%\n" +
	"\x05speed\x18\b \x01(\x0e2\x0f.packets.SpeedsR\x05speed\x12\x1a\n" +
	"\bUnitName\x18\t \x01(\tR\bUnitName\x12%\n" +
	"\x03Pos\x18\n" +
	" \x01(\v2\x13.packets.Vector3MsgR\x03Pos\"_\n" +
	"\x13UnitPositionMessage\x12\x16\n" +
	"\x06unitId\x18\x01 \x01(\x05R\x06unitId\x120\n" +
	"\bPosition\x18\x02 \x01(\v2\x14.packets.Vector2IMsgR\bPosition\"J\n" +
	"\x14UnitPositionsMessage\x122\n" +
	"\x05units\x18\x01 \x03(\v2\x1c.packets.UnitPositionMessageR\x05units\"\xcb\x01\n" +
	"\x0fGameDataMessage\x122\n" +
	"\aversion\x18\x01 \x01(\v2\x18.packets.GameDataVersionR\aversion\x120\n" +
	"\bfactions\x18\x02 \x03(\v2\x14.packets.FactionDataR\bfactions\x12)\n" +
	"\x06armies\x18\x03 \x03(\v2\x11.packets.ArmyDataR\x06armies\x12'\n" +
	"\x05units\x18\x04 \x03(\v2\x11.packets.UnitDataR\x05units\"+\n" +
	"\x0fGameDataVersion\x12\x18\n" +
	"\aVersion\x18\x01 \x01(\tR\aVersion\"\x1f\n" +
	"\rArmyIDMessage\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\":\n" +
	"\x0eUnitIDsMessage\x12(\n" +
	"\x03ids\x18\x01 \x03(\v2\x16.packets.UnitIDMessageR\x03ids\"7\n" +
	"\rUnitIDMessage\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\x12\x16\n" +
	"\x06unitId\x18\x02 \x01(\x05R\x06unitId\"\xbc\n" +
	"\n" +
	"\x06Packet\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x04R\bsenderId\x12*\n" +
	"\x04chat\x18\x02 \x01(\v2\x14.packets.ChatMessageH\x00R\x04chat\x12$\n" +
	"\x02id\x18\x03 \x01(\v2\x12.packets.IdMessageH\x00R\x02id\x12B\n" +
	"\floginRequest\x18\x04 \x01(\v2\x1c.packets.LoginRequestMessageH\x00R\floginRequest\x12K\n" +
	"\x0fregisterRequest\x18\x05 \x01(\v2\x1f.packets.RegisterRequestMessageH\x00R\x0fregisterRequest\x12,\n" +
	"\x02OK\x18\x06 \x01(\v2\x1a.packets.OkResponseMessageH\x00R\x02OK\x122\n" +
	"\x04Deny\x18\a \x01(\v2\x1c.packets.DenyResponseMessageH\x00R\x04Deny\x123\n" +
	"\acommand\x18\b \x01(\v2\x17.packets.CommandMessageH\x00R\acommand\x12?\n" +
	"\vhexPosition\x18\t \x01(\v2\x1b.packets.HexPositionMessageH\x00R\vhexPosition\x12B\n" +
	"\fhexPositions\x18\n" +
	" \x01(\v2\x1c.packets.HexPositionsMessageH\x00R\fhexPositions\x12C\n" +
	"\vsteamTicket\x18\v \x01(\v2\x1f.packets.SteamAuthTicketMessageH\x00R\vsteamTicket\x12?\n" +
	"\vchangeState\x18\f \x01(\v2\x1b.packets.ChangeStateMessageH\x00R\vchangeState\x12-\n" +
	"\x05queue\x18\r \x01(\v2\x15.packets.QueueMessageH\x00R\x05queue\x126\n" +
	"\bopponent\x18\x0e \x01(\v2\x18.packets.OpponentMessageH\x00R\bopponent\x129\n" +
	"\tstartGame\x18\x0f \x01(\v2\x19.packets.StartGameMessageH\x00R\tstartGame\x12*\n" +
	"\x04seed\x18\x10 \x01(\v2\x14.packets.SeedMessageH\x00R\x04seed\x12'\n" +
	"\x03IDs\x18\x11 \x01(\v2\x13.packets.IDsMessageH\x00R\x03IDs\x12*\n" +
	"\x04Unit\x18\x12 \x01(\v2\x14.packets.UnitMessageH\x00R\x04Unit\x126\n" +
	"\bGameData\x18\x13 \x01(\v2\x18.packets.GameDataMessageH\x00R\bGameData\x12<\n" +
	"\vGameVersion\x18\x14 \x01(\v2\x18.packets.GameDataVersionH\x00R\vGameVersion\x120\n" +
	"\x06ArmyId\x18\x15 \x01(\v2\x16.packets.ArmyIDMessageH\x00R\x06ArmyId\x12B\n" +
	"\fUnitPosition\x18\x16 \x01(\v2\x1c.packets.UnitPositionMessageH\x00R\fUnitPosition\x12E\n" +
	"\rUnitPositions\x18\x17 \x01(\v2\x1d.packets.UnitPositionsMessageH\x00R\rUnitPositions\x123\n" +
	"\aUnitIds\x18\x18 \x01(\v2\x17.packets.UnitIDsMessageH\x00R\aUnitIdsB\x05\n" +
	"\x03msg*B\n" +
	"\bChatType\x12\v\n" +
	"\aNothing\x10\x00\x12\n" +
	"\n" +
	"\x06Global\x10\x01\x12\t\n" +
	"\x05Local\x10\x02\x12\t\n" +
	"\x05Party\x10\x03\x12\a\n" +
	"\x03Max\x10\x04*(\n" +
	"\x06Speeds\x12\n" +
	"\n" +
	"\x06Normal\x10\x00\x12\b\n" +
	"\x04Slow\x10\x01\x12\b\n" +
	"\x04Fast\x10\x02B\rZ\vpkg/packetsb\x06proto3"

var (
	file_packets_proto_rawDescOnce sync.Once
	file_packets_proto_rawDescData []byte
)

func file_packets_proto_rawDescGZIP() []byte {
	file_packets_proto_rawDescOnce.Do(func() {
		file_packets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packets_proto_rawDesc), len(file_packets_proto_rawDesc)))
	})
	return file_packets_proto_rawDescData
}

var file_packets_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_packets_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_packets_proto_goTypes = []any{
	(ChatType)(0),                  // 0: packets.ChatType
	(Speeds)(0),                    // 1: packets.Speeds
	(*Vector3Msg)(nil),             // 2: packets.Vector3Msg
	(*Vector2Msg)(nil),             // 3: packets.Vector2Msg
	(*Vector2IMsg)(nil),            // 4: packets.Vector2IMsg
	(*FactionData)(nil),            // 5: packets.FactionData
	(*ArmyData)(nil),               // 6: packets.ArmyData
	(*UnitArmyData)(nil),           // 7: packets.UnitArmyData
	(*UnitData)(nil),               // 8: packets.UnitData
	(*ChatMessage)(nil),            // 9: packets.ChatMessage
	(*IdMessage)(nil),              // 10: packets.IdMessage
	(*LoginRequestMessage)(nil),    // 11: packets.LoginRequestMessage
	(*SteamAuthTicketMessage)(nil), // 12: packets.SteamAuthTicketMessage
	(*RegisterRequestMessage)(nil), // 13: packets.RegisterRequestMessage
	(*OkResponseMessage)(nil),      // 14: packets.OkResponseMessage
	(*DenyResponseMessage)(nil),    // 15: packets.DenyResponseMessage
	(*CommandMessage)(nil),         // 16: packets.CommandMessage
	(*ChangeStateMessage)(nil),     // 17: packets.ChangeStateMessage
	(*QueueMessage)(nil),           // 18: packets.QueueMessage
	(*HexPositionMessage)(nil),     // 19: packets.HexPositionMessage
	(*HexPositionsMessage)(nil),    // 20: packets.HexPositionsMessage
	(*OpponentMessage)(nil),        // 21: packets.OpponentMessage
	(*StartGameMessage)(nil),       // 22: packets.StartGameMessage
	(*SeedMessage)(nil),            // 23: packets.SeedMessage
	(*IDsMessage)(nil),             // 24: packets.IDsMessage
	(*UnitMessage)(nil),            // 25: packets.UnitMessage
	(*UnitPositionMessage)(nil),    // 26: packets.UnitPositionMessage
	(*UnitPositionsMessage)(nil),   // 27: packets.UnitPositionsMessage
	(*GameDataMessage)(nil),        // 28: packets.GameDataMessage
	(*GameDataVersion)(nil),        // 29: packets.GameDataVersion
	(*ArmyIDMessage)(nil),          // 30: packets.ArmyIDMessage
	(*UnitIDsMessage)(nil),         // 31: packets.UnitIDsMessage
	(*UnitIDMessage)(nil),          // 32: packets.UnitIDMessage
	(*Packet)(nil),                 // 33: packets.Packet
}
var file_packets_proto_depIdxs = []int32{
	7,  // 0: packets.ArmyData.unitIds:type_name -> packets.UnitArmyData
	1,  // 1: packets.UnitData.Speed:type_name -> packets.Speeds
	0,  // 2: packets.ChatMessage.type:type_name -> packets.ChatType
	3,  // 3: packets.HexPositionMessage.position:type_name -> packets.Vector2Msg
	19, // 4: packets.HexPositionsMessage.positions:type_name -> packets.HexPositionMessage
	10, // 5: packets.IDsMessage.IDs:type_name -> packets.IdMessage
	1,  // 6: packets.UnitMessage.speed:type_name -> packets.Speeds
	2,  // 7: packets.UnitMessage.Pos:type_name -> packets.Vector3Msg
	4,  // 8: packets.UnitPositionMessage.Position:type_name -> packets.Vector2IMsg
	26, // 9: packets.UnitPositionsMessage.units:type_name -> packets.UnitPositionMessage
	29, // 10: packets.GameDataMessage.version:type_name -> packets.GameDataVersion
	5,  // 11: packets.GameDataMessage.factions:type_name -> packets.FactionData
	6,  // 12: packets.GameDataMessage.armies:type_name -> packets.ArmyData
	8,  // 13: packets.GameDataMessage.units:type_name -> packets.UnitData
	32, // 14: packets.UnitIDsMessage.ids:type_name -> packets.UnitIDMessage
	9,  // 15: packets.Packet.chat:type_name -> packets.ChatMessage
	10, // 16: packets.Packet.id:type_name -> packets.IdMessage
	11, // 17: packets.Packet.loginRequest:type_name -> packets.LoginRequestMessage
	13, // 18: packets.Packet.registerRequest:type_name -> packets.RegisterRequestMessage
	14, // 19: packets.Packet.OK:type_name -> packets.OkResponseMessage
	15, // 20: packets.Packet.Deny:type_name -> packets.DenyResponseMessage
	16, // 21: packets.Packet.command:type_name -> packets.CommandMessage
	19, // 22: packets.Packet.hexPosition:type_name -> packets.HexPositionMessage
	20, // 23: packets.Packet.hexPositions:type_name -> packets.HexPositionsMessage
	12, // 24: packets.Packet.steamTicket:type_name -> packets.SteamAuthTicketMessage
	17, // 25: packets.Packet.changeState:type_name -> packets.ChangeStateMessage
	18, // 26: packets.Packet.queue:type_name -> packets.QueueMessage
	21, // 27: packets.Packet.opponent:type_name -> packets.OpponentMessage
	22, // 28: packets.Packet.startGame:type_name -> packets.StartGameMessage
	23, // 29: packets.Packet.seed:type_name -> packets.SeedMessage
	24, // 30: packets.Packet.IDs:type_name -> packets.IDsMessage
	25, // 31: packets.Packet.Unit:type_name -> packets.UnitMessage
	28, // 32: packets.Packet.GameData:type_name -> packets.GameDataMessage
	29, // 33: packets.Packet.GameVersion:type_name -> packets.GameDataVersion
	30, // 34: packets.Packet.ArmyId:type_name -> packets.ArmyIDMessage
	26, // 35: packets.Packet.UnitPosition:type_name -> packets.UnitPositionMessage
	27, // 36: packets.Packet.UnitPositions:type_name -> packets.UnitPositionsMessage
	31, // 37: packets.Packet.UnitIds:type_name -> packets.UnitIDsMessage
	38, // [38:38] is the sub-list for method output_type
	38, // [38:38] is the sub-list for method input_type
	38, // [38:38] is the sub-list for extension type_name
	38, // [38:38] is the sub-list for extension extendee
	0,  // [0:38] is the sub-list for field type_name
}

func init() { file_packets_proto_init() }
func file_packets_proto_init() {
	if File_packets_proto != nil {
		return
	}
	file_packets_proto_msgTypes[31].OneofWrappers = []any{
		(*Packet_Chat)(nil),
		(*Packet_Id)(nil),
		(*Packet_LoginRequest)(nil),
		(*Packet_RegisterRequest)(nil),
		(*Packet_OK)(nil),
		(*Packet_Deny)(nil),
		(*Packet_Command)(nil),
		(*Packet_HexPosition)(nil),
		(*Packet_HexPositions)(nil),
		(*Packet_SteamTicket)(nil),
		(*Packet_ChangeState)(nil),
		(*Packet_Queue)(nil),
		(*Packet_Opponent)(nil),
		(*Packet_StartGame)(nil),
		(*Packet_Seed)(nil),
		(*Packet_IDs)(nil),
		(*Packet_Unit)(nil),
		(*Packet_GameData)(nil),
		(*Packet_GameVersion)(nil),
		(*Packet_ArmyId)(nil),
		(*Packet_UnitPosition)(nil),
		(*Packet_UnitPositions)(nil),
		(*Packet_UnitIds)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packets_proto_rawDesc), len(file_packets_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packets_proto_goTypes,
		DependencyIndexes: file_packets_proto_depIdxs,
		EnumInfos:         file_packets_proto_enumTypes,
		MessageInfos:      file_packets_proto_msgTypes,
	}.Build()
	File_packets_proto = out.File
	file_packets_proto_goTypes = nil
	file_packets_proto_depIdxs = nil
}
